name: "First Workflow"
on:
 # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: display the tasks
        run: echo"disply the tasks"
      - name: execute the shell commands
        run: pwd
