name: "Build Job"
on:
 # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: display the tasks
        run: echo "disply the tasks"
      - name: execute the shell commands
        run: pwd
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: execute the python script
        run: |
           ls -al
           pwd
           python abcd.py
